name: rozvp
version: '0.1.0'
summary: Clone of my Godot template for bevy
description: |
  A complete Bevy 2D game template with ecosystem plugins,
  game feel, transitions, audio, save system, and more.
grade: stable
confinement: strict

apps:
  rozvp:
    command: rozvp
    plugs: [x11, wayland, audio, joystick]

parts:
  rozvp:
    plugin: rust
    source: .
